AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      OpenApiVersion: 3.0.2
      DefinitionBody: !Transform
        Name: AWS::Include
        Parameters:
          Location: api-spec.yaml
      TracingEnabled: true
      Cors:
        MaxAge: 5
        AllowOrigin: '''www.localhost:4200/**'''
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x

      CodeUri: function/.
      Description: Call the AWS Lambda API
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Tracing: Active
      Events:
        postEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref api
            Path: /
            Method: POST
